version: "3.8"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  humans-1:
    image: humans-service
    networks:
      app_net:
        ipv4_address: 172.20.0.10
    depends_on:
      - wildfly
      - consul
      - postgres
      - zookeeper
      - kafka
      - haproxy
    volumes:
      - ./utils/humans-1:/app/config
  humans-2:
    image: humans-service
    networks:
      app_net:
        ipv4_address: 172.20.0.11
    depends_on:
      - wildfly
      - consul
      - postgres
      - zookeeper
      - kafka
      - haproxy
    volumes:
      - ./utils/humans-2:/app/config
  teams-soap:
    image: teams-soap
    networks:
      app_net:
        ipv4_address: 172.20.0.12
    depends_on:
      - wildfly
      - consul
      - postgres
      - zookeeper
      - kafka
      - haproxy
    volumes:
      - ./utils/teams-1:/app/config
  teams-rest:
    image: teams-rest
    networks:
      app_net:
        ipv4_address: 172.20.0.13
    depends_on:
      - wildfly
      - consul
      - postgres
      - zookeeper
      - kafka
      - haproxy
    volumes:
      - ./utils/teams-2:/app/config

  wildfly:
    image: jboss/wildfly:latest
    container_name: wildfly
    ports:
      - "8080:8080"
      - "8585:8585"
      - "8443:8443"
      - "9990:9990"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASSWORD=admin
    depends_on:
      - postgres
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      /bin/bash -c "
      /opt/jboss/wildfly/bin/add-user.sh admin admin --silent &&
      /opt/jboss/wildfly/bin/add-user.sh user user -a --silent &&
      /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -Djboss.bind.address.management=0.0.0.0 -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.private=0.0.0.0 -Djboss.bind.address.unsecure=0.0.0.0
      "
    # volumes:
    #   - ./teams-service/target:/opt/jboss/wildfly/standalone/deployments
    networks:
      app_net:
        ipv4_address: 172.20.0.14

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      app_net:
        ipv4_address: 172.20.0.15

  postgres-teams:
    image: postgres:latest
    container_name: postgres-teams
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    networks:
      app_net:
        ipv4_address: 172.20.0.25

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.7.7
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      app_net:
        ipv4_address: 172.20.0.16

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.7.7
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.20.0.17:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      app_net:
        ipv4_address: 172.20.0.17

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      app_net:
        ipv4_address: 172.20.0.18

  haproxy:
    image: haproxy:3.0
    container_name: haproxy
    ports:
      - "8088:8088"
      - "9081:9081"
      - "9018:9018"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - wildfly
      - consul
    networks:
      app_net:
        ipv4_address: 172.20.0.19
