version: "3.8"

services:
  wildfly:
    image: jboss/wildfly:latest
    container_name: wildfly
    ports:
      - "8080:8080"
      - "8081:8443"
      - "9990:9990"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASSWORD=admin
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASSWORD=1
    depends_on:
      - postgres
    command: >
      /bin/bash -c "
      /opt/jboss/wildfly/bin/add-user.sh admin admin --silent && 
      /opt/jboss/wildfly/bin/add-user.sh user user -a --silent &&
      /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
      "

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
